### ISSUE TITLE
Build Issue

### ISSUE THREAD

**Issue by FareedQ** [czechboy0/swift-package-crawler#1]
Hi Czechboy0,
I am interested in this project and seeing the dependancy landscape of Swift projects. I tried to go through running this crawler, but it is failing to build for me. I got Swift 3.0 and am using the package manager to build (Swift Build) but it seems one of the dependancies is has an issue (PureJSON). Do you have the same issue building, and if so how do you get around one of the dependencies failing?

Thanks,
Fareed

**Comment by czechboy0** [comment]
Hi @FareedQ,

I made a few hacks to get it working, now it should work for you (tested on the dev snapshot 05-31, not on the preview, but the dev snapshot).

Also please make sure you have a Redis server running locally on the default port. And that this actually points to your latest swift binary: https://github.com/czechboy0/swift-package-crawler/blob/master/Sources/PackageExporterLib/Converter.swift#L23

**Comment by FareedQ** [comment]
Thank you,
I appreciate the community support :)

On Fri, Jun 3, 2016 at 5:49 AM, Honza Dvorsky <notifications@github.com>
wrote:

> Hi @FareedQ <https://github.com/FareedQ>,
>
> I made a few hacks to get it working, now it should work for you (tested
> on the dev snapshot 05-31, not on the preview, but the dev snapshot).
>
> Also please make sure you have a Redis server running locally on the
> default port. And that this actually points to your latest swift binary:
> https://github.com/czechboy0/swift-package-crawler/blob/master/Sources/PackageExporterLib/Converter.swift#L23
>
> —
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub
> <https://github.com/czechboy0/swift-package-crawler/issues/1#issuecomment-223537903>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEzUkzDb5i_9iGUpRDzsTHibJ5Trnk1zks5qH_iRgaJpZM4ItC-V>
> .
>



-- 
www.FareedQ.com
Twitter @IAmFareedQ
