### ISSUE TITLE
My repo not showing up

### ISSUE THREAD

**Issue by FareedQ** [czechboy0/swift-package-crawler#2]
Hey @czechboy0,
I was playing with this tool you built, and I tried copying one of the repos your crawler captures to see if my name would show up in the results. It did not. This was the repo I was looking for https://github.com/FareedQ/testRepo.

Further investigation I found that the number of repos it captures seem to be inconsistent. I put a second versions of the app on my computer in a different folder and ran it to find 46 more repos in it's cache folder (my test repo didn't show up).

Does it take a certain amount of time after a repo is committed to github before it shows up?

I'm going to play around with it some more, but was hoping you could help me understand the tool.

**Comment by czechboy0** [comment]
The crawler uses GitHub search by actually pretending to be a browser and parsing the returned HTML. GitHub search sometimes returns inconsistent results, so unfortunately I can't do any better. The trick is to run it twice or three times a day after which you should get most the results, but by no means is it 100% deterministic. 

Technically you could add your repo to the list (in the Redis db it's a set under the key github_names after which it'll be crawled as well. Just the GitHub search crawling is used for discovering new packages.)

**Comment by FareedQ** [comment]
Thank you for the suggestion.

Yes, looking at the code I realize you are being limited by Github's
search. Thanks again.

On Tue, Jun 7, 2016 at 2:04 AM, Honza Dvorsky <notifications@github.com>
wrote:

> The crawler uses GitHub search by actually pretending to be a browser and
> parsing the returned HTML. GitHub search sometimes returns inconsistent
> results, so unfortunately I can't do any better. The trick is to run it
> twice or three times a day after which you should get most the results, but
> by no means is it 100% deterministic.
>
> Technically you could add your repo to the list (in the Redis db it's a
> set under the key github_names after which it'll be crawled as well. Just
> the GitHub search crawling is used for discovering new packages.)
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub
> <https://github.com/czechboy0/swift-package-crawler/issues/2#issuecomment-224187465>,
> or mute the thread
> <https://github.com/notifications/unsubscribe/AEzUkzSyc5ze36TH__dwTZQQfY2_qkE1ks5qJQnbgaJpZM4IvWcN>
> .
>



-- 
www.FareedQ.com
Twitter @IAmFareedQ
